"""
This GENS mode code which be ported from GENS source code.
@@OAX4K dist define

Author: OVT AE
Date: 2024-11-04
"""
# WARNING
# pylint: disable=C0103, W0401, W0614
from Define.board import *
define_dist = {
    "ANALOG": [ANALOG_BASE_ADDR],
    "CLOCK_MONITOR": (CLKMNR0_BASE_ADDR, CLKMNR1_BASE_ADDR, CLKMNR2_BASE_ADDR, CLKMNR3_BASE_ADDR,
                      CLKMNR4_BASE_ADDR, CLKMNR5_BASE_ADDR, CLKMNR6_BASE_ADDR, CLKMNR7_BASE_ADDR,
                      CLKMNR8_BASE_ADDR, CLKMNR9_BASE_ADDR, CLKMNR10_BASE_ADDR, CLKMNR11_BASE_ADDR,
                      CLKMNR12_BASE_ADDR, CLKMNR13_BASE_ADDR, CLKMNR14_BASE_ADDR, CLKMNR15_BASE_ADDR,
                      CLKMNR16_BASE_ADDR, CLKMNR17_BASE_ADDR),
    "CPU2TAP": [C2T_BASE_ADDR],  # tbd
    "CRYPTO": [CRYPTO_BASE_ADDR],
    "COLOR_BAR": (CB0_BASE_ADDR, CB1_BASE_ADDR, CB2_BASE_ADDR, CB3_BASE_ADDR),
    "EDMA": [DMA_BASE_ADDR],
    "EFUSE_256X32": [EFUSE0_BASE_ADDR],
    "EFUSE_32X32": [EFUSE1_BASE_ADDR],
    "EMB": (EMB0_BASE_ADDR, EMB1_BASE_ADDR, EMB2_BASE_ADDR, EMB3_BASE_ADDR),
    "FCP": [FCP_BASE_ADDR],
    "GTW": [GTW_BASE_ADDR],
    "IDC_USUAL": [IDC_BASE_ADDR],
    "IDP_USUAL": [IDP_BASE_ADDR],
    "IDC_PATH": [IDC0_BASE_ADDR, IDC1_BASE_ADDR, IDC2_BASE_ADDR, IDC3_BASE_ADDR],
    "IDP_PATH": [IDP0_BASE_ADDR, IDP1_BASE_ADDR, IDP2_BASE_ADDR, IDP3_BASE_ADDR],
    # "ITPG": (ITPG0_BASE_ADDR, ITPG1_BASE_ADDR, ITPG2_BASE_ADDR, ITPG3_BASE_ADDR),
    "IMAGE_MONITOR": (IM0_BASE_ADDR, IM1_BASE_ADDR, IM2_BASE_ADDR, IM3_BASE_ADDR),
    "MIPI_RX_2L": (MRX1_BASE_ADDR, MRX3_BASE_ADDR),
    "MIPI_RX_4L": (MRX0_BASE_ADDR, MRX2_BASE_ADDR),
    "MIPIRX": (MRX0_BASE_ADDR, MRX1_BASE_ADDR, MRX2_BASE_ADDR, MRX3_BASE_ADDR),
    # "MIPI_TX_CHN4": (MTX1_BASE_ADDR, MTX3_BASE_ADDR),
    # "MIPI_TX_CHN8": (MTX0_BASE_ADDR, MTX2_BASE_ADDR),
    "MIPI_TX_CHN8": [MTX0_BASE_ADDR],
    "MIPI_TX_CHN4": (MTX1_BASE_ADDR, MTX2_BASE_ADDR, MTX3_BASE_ADDR),
    "MIPITX": (MTX0_BASE_ADDR, MTX1_BASE_ADDR, MTX2_BASE_ADDR, MTX3_BASE_ADDR),
    "PAD": [PAD_BASE_ADDR],
    "RETIME": (RETIME0_BASE_ADDR, RETIME1_BASE_ADDR, RETIME2_BASE_ADDR, RETIME3_BASE_ADDR),
    "RGBIR_CIP": (CIP0_BASE_ADDR, CIP1_BASE_ADDR, CIP2_BASE_ADDR, CIP3_BASE_ADDR),
    "RGBIR_DPC": (DPC0_BASE_ADDR, DPC1_BASE_ADDR, DPC2_BASE_ADDR, DPC3_BASE_ADDR),
    "RGBIR_IRRM_NEW": (IRRM_NEW0_BASE_ADDR, IRRM_NEW1_BASE_ADDR, IRRM_NEW2_BASE_ADDR, IRRM_NEW3_BASE_ADDR),
    "RGBIR_IRRM": (IRRM0_BASE_ADDR, IRRM1_BASE_ADDR, IRRM2_BASE_ADDR, IRRM3_BASE_ADDR),
    "RGBIR": (RGBIR_TOP0_BASE_ADDR, RGBIR_TOP1_BASE_ADDR, RGBIR_TOP2_BASE_ADDR, RGBIR_TOP3_BASE_ADDR),
    "RGBIR_TOP": (RGBIR_TOP0_BASE_ADDR, RGBIR_TOP1_BASE_ADDR, RGBIR_TOP2_BASE_ADDR, RGBIR_TOP3_BASE_ADDR),
    "RGBIR_UVDNS": (DNS0_BASE_ADDR, DNS1_BASE_ADDR, DNS2_BASE_ADDR, DNS3_BASE_ADDR),
    "SCCB_MASTER": (SCCBM0_BASE_ADDR, SCCBM1_BASE_ADDR),
    "SCCB_MS": [SCCBMS_BASE_ADDR],
    "SC": [SC_BASE_ADDR],
    "SYSTEM_CTRL": [SC_BASE_ADDR],
    "ECC": [SC_BASE_ADDR],
    "SHA": [SHA_BASE_ADDR],
    "SPI_MASTER": [SPIM_BASE_ADDR],
    "SPI_SLAVE": [SPIS_BASE_ADDR],
    "TPM": [TPM_BASE_ADDR],
    "VM": [VM_BASE_ADDR],
    "UART": [UART_BASE_ADDR],
    "ISP": [ISP_REG_BASE_ADDR, ISP_REG_BASE_ADDR + 0x2000, ISP_REG_BASE_ADDR + 0x4000, ISP_REG_BASE_ADDR + 0x6000],
    "PGEN": [PGEN0_BASE_ADDR, PGEN1_BASE_ADDR],
    "ECM": [ECM_BASE_ADDR],
    "HW_CRC": [HWCRC_BASE_ADDR],
}

dp_reglen_boardcast_dist = {
    "COLOR_BAR": 0x100,
    "EMB": 0x80,
    "IDC_PATH": 0x80,
    "IDP_PATH": 0x40,
    # "ITPG": (ITPG0_BASE_ADDR ,ITPG1_BASE_ADDR,ITPG2_BASE_ADDR,ITPG3_BASE_ADDR),
    "IMAGE_MONITOR": 0x80,
    "MIPI_RX": 0x300,
    # "MIPI_TX_CHN4": (MTX1_BASE_ADDR ,MTX3_BASE_ADDR),
    # "MIPI_TX_CHN8": (MTX0_BASE_ADDR ,MTX2_BASE_ADDR),
    "MIPI_TX": 0x400,
    "RETIME": 0x100,
    "RGBIR": 0x400,
    "RGBIR_TOP": 0x400,
    "ISP": 0x2000
}
