# tools/bin2py.py
import os
import sys

def convert(bin_path, out_py_file):
    # 檢查來源 BIN 檔案是否存在
    if not os.path.exists(bin_path):
        print(f"Error: Source file {bin_path} not found.")
        sys.exit(1)
    # 讀取二進位資料
    with open(bin_path, "rb") as bin_f:
        data = bin_f.read()
    # 如果目標 .py 檔案已存在，先將其刪除（確保重新建立）
    if os.path.exists(out_py_file):
        try:
            os.remove(out_py_file)
        except Exception as e:
            print(f"Warning: Could not remove old file {out_py_file}: {e}")
    # 建立新檔案並寫入內容
    # "w" 模式會自動建立不存在的檔案，或覆蓋已存在的檔案
    try:
        with open(out_py_file, "w", encoding="utf-8") as f:
            f.write("# Generated by CMake - DO NOT EDIT\n")
            # 使用 repr(data) 產生 b'\x00...' 格式
            f.write(f"FW_BYTES_ATB = {repr(data)}\n")
        print(f"Successfully converted {bin_path} to {out_py_file}")
    except Exception as e:
        print(f"Error writing to {out_py_file}: {e}")
        sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) >= 3:
        convert(sys.argv[1], sys.argv[2])
    else:
        print("Usage: python bin2py.py <input_bin> <output_py>")
